/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from 'next'
import Head from 'next/head'

import { EmploymentFormsHeader } from '@/components/layout'
import Link from 'next/link'

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lisa ann shaw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-[auto] w-full bg-[url('/images/bg.jpg')] bg-cover bg-bottom bg-no-repeat">
        <EmploymentFormsHeader />

        <div className="section-header_container">
          <div className="align-center flex justify-evenly pt-[10%]">
            <div className="col-lg-6">
              <div className="content pt-32">
                <h4 data-animation="animated slideInLeft">FINANCIAL ADVISOR</h4>
                <h2 data-animation="animated slideInRight">LISA ELLEN SHAW</h2>
                <Link href="https://brokercheck.finra.org/individual/summary/5225542">
                  <a
                    data-animation="animated slideInLeft"
                    className="btn btn-gradient effect btn-md"
                    target="_blank"
                  >
                    Detailed Report
                  </a>
                </Link>
              </div>
            </div>
            <div className="col-lg-6 thumb">
              <div
                className="shape-thumb h-[500px] w-[500px] bg-[url('/images/4.png')]"
                data-animation="animated slideInUp"
              >
                {/* <img src={Image1} alt="Thumb" /> */}
              </div>
            </div>
          </div>
        </div>

        {/* <EmploymentFormsFooter /> */}
      </div>
      <section className="services-section h-[auto] w-full bg-[#1b1b1b] py-[120px]">
        <div id="services" className="thumbs-services-area bg-dark text-light default-padding">
          <div className="container">
            <div className="row">
              <div className="col-lg-8 offset-lg-2">
                <div className="site-heading text-center">
                  <h4 className="st-current">My Services</h4>
                  <h2 className="">What We Bring To You</h2>
                  <div className="devider"></div>
                </div>
              </div>
            </div>
          </div>

          <div className="container-services mx-[auto] max-w-[1200px]">
            <div className="services-content">
              <div className="row">
                <div className="col-lg-12">
                  <div className="thumb-services-carousel owl-carousel owl-theme owl-loaded owl-drag">
                    <div className="owl-stage-outer">
                      <div
                        className="owl-stage"
                        style={{
                          transform: 'translate3d(0px, 0px, 0px)',
                          transition: 'all 0s ease 0s',
                          // width: "1600px",
                        }}
                      >
                        <div className="parent-container flex max-w-[1200px] overflow-x-auto scrollbar-hide">
                          <div className=" flex">
                            <div className="flex flex-col items-center justify-center">
                              <div className="z-40 mr-[30px] h-[191px] w-[340px]  rounded-[7px] bg-[url('/images/Financ-Consul.jpg')] bg-cover bg-center"></div>
                              <div className="owl-item active relative -z-40 mt-[-60px]  mr-[30px] box-border h-[300px] w-[370px] rounded-[7px] bg-[#24282b] p-[30px]">
                                <div className="item absolute flex flex-col items-center justify-center">
                                  <div className="info mt-20">
                                    <h4 className="info-header">
                                      <a href="services-single.html">FINANCIAL CONSULTING</a>
                                    </h4>
                                    <p className="info-para">
                                      Critical evaluation with deep insight on investment in
                                      efficiently handling financial portfolios with consistent
                                      profits.
                                    </p>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div className="flex flex-col items-center justify-center">
                              <div className="z-40 mr-[30px] h-[191px] w-[340px]  rounded-[7px] bg-[url('/images/Invest-Strategy.jpg')] bg-cover bg-center"></div>
                              <div className="owl-item active relative -z-40 mt-[-60px]  mr-[30px] box-border h-[300px] w-[370px] rounded-[7px] bg-[#24282b] p-[30px]">
                                <div className="item absolute flex flex-col items-center justify-center">
                                  <div className="info mt-20">
                                    <h4 className="info-header">
                                      <a href="services-single.html"> INVESTMENT STRATEGY</a>
                                    </h4>
                                    <p className="info-para">
                                      My insights on Investment could make you consistent profits in
                                      the financial markets.
                                    </p>
                                  </div>
                                </div>
                              </div>
                            </div>

                            <div className="flex flex-col items-center justify-center">
                              <div className="z-40 mr-[30px] h-[191px] w-[340px]  rounded-[7px] bg-[url('/images/stock-market.jpg')] bg-cover bg-center"></div>
                              <div className="owl-item active relative -z-40 mt-[-60px]  mr-[30px] box-border h-[300px] w-[370px] rounded-[7px] bg-[#24282b] p-[30px]">
                                <div className="item absolute flex flex-col items-center justify-center">
                                  <div className="info mt-20">
                                    <h4 className="info-header">
                                      <a href="services-single.html">STOCK BROKERAGE</a>
                                    </h4>
                                    <p className="info-para">
                                      Buying of stocks strategically and selling at profitable
                                      margins.
                                    </p>
                                  </div>
                                </div>
                              </div>
                            </div>

                            <div className="flex flex-col items-center justify-center">
                              <div className="z-40 mr-[30px] h-[191px] w-[340px]  rounded-[7px] bg-[url('/images/digital-asset-trading.jpg')] bg-cover bg-center"></div>
                              <div className="owl-item active relative -z-40 mt-[-60px]  mr-[30px] box-border h-[300px] w-[370px] rounded-[7px] bg-[#24282b] p-[30px]">
                                <div className="item absolute flex flex-col items-center justify-center">
                                  <div className="info mt-20">
                                    <h4 className="info-header">
                                      <a href="services-single.html">DIGITAL ASSETS TRADING</a>
                                    </h4>
                                    <p className="info-para">
                                      Investing a portion of your profits in the most reliable
                                      digital currencies so as to be part of the future.
                                    </p>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="owl-nav disabled">
                      <div className="owl-prev">
                        <i className="fa fa-angle-left"></i>
                      </div>
                      <div className="owl-next">
                        <i className="fa fa-angle-right"></i>
                      </div>
                    </div>
                    <div className="owl-dots">
                      <div className="owl-dot active">
                        <span></span>
                      </div>
                      <div className="owl-dot">
                        <span></span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <div id="about" className="about-us-area default-padding bg-gray  h-[auto] py-[120px]">
        <div className="container max-w-[1400px]">
          <div className="about-items">
            <div className="row align-center flex items-center gap-[50px]">
              <div className="col-lg-6">
                <div className="thumb flex h-full">
                  <div className="z-50 flex flex-col justify-between pb-16">
                    <div className="h-[250px] w-[25px] rounded-lg bg-[#1273eb]"></div>
                    <h2 className="bottom-[50px] mb-[50px] whitespace-nowrap px-[37px] text-base">
                      <strong className="text-[62px] leading-[68.2px] text-[#1273eb]">16</strong>
                      years of <br /> working experience
                    </h2>
                  </div>
                  <div className="-ml-40 h-[650px] w-[570px] bg-[url('/images/img2.jpeg')]"></div>
                </div>
              </div>
              <div className="col-lg-6 info">
                <h2>
                  "In investing, what is comfortable <br /> is rarely profitable."
                </h2>
                <p className="text-left leading-7 tracking-normal">
                  I am Lisa Ellen Shaw, A Financial Consultant and Stock Broker with 16 years of
                  experience worked with more than 3 prestigious brokerage firms in the U.S. At the
                  moment, I partner with FIDELITY BROKERAGE SERVICES LLC (CRD#: 7784) where I help
                  clients meet their desired financial targets with strategic investing in the
                  stock, digital &amp; foreign exchange market. I have obtained Fifty-five (55)
                  State Registration Licenses and passed four(4) Brokerage Qualification
                  Examinations.
                </p>
                <ul>
                  <li className="flex items-center gap-2">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="15"
                      height="15"
                      fill="#1273eb"
                      viewBox="0 0 256 256"
                    >
                      <path d="M229.66,77.66l-128,128a8,8,0,0,1-11.32,0l-56-56a8,8,0,0,1,11.32-11.32L96,188.69,218.34,66.34a8,8,0,0,1,11.32,11.32Z"></path>
                    </svg>
                    800+ Profiles Handled
                  </li>
                  <li className="flex items-center gap-2">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="15"
                      height="15"
                      fill="#1273eb"
                      viewBox="0 0 256 256"
                    >
                      <path d="M229.66,77.66l-128,128a8,8,0,0,1-11.32,0l-56-56a8,8,0,0,1,11.32-11.32L96,188.69,218.34,66.34a8,8,0,0,1,11.32,11.32Z"></path>
                    </svg>
                    $120 Million in accumulated profits
                  </li>
                </ul>
                <div className="author mt-[31px] flex">
                  <div className="signature">
                    <div className="h-[80px] w-[139.42px]  bg-[url('/images/signature.png')] bg-cover bg-center bg-no-repeat"></div>
                  </div>
                  <div className="intro">
                    <h5>Lisa Ellen Shaw</h5>
                    <span>Financial Consulting | Investment Advisory &amp; Stock Brokerage</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="expertise-area default-padding py-[120px]">
        <div className="container max-w-[1300px]">
          <div className="item-heading">
            <div className="row -mx-[15px] flex flex-wrap">
              <div className="col-lg-6 info basis-1/2">
                <h4>My expertise</h4>
              </div>
              <div className="col-lg-6 right-info basis-1/2">
                <div className="skill-items">
                  <div className="progress-box">
                    <h5>Financial Consulting</h5>
                    <div className="progress">
                      <div className="progress-bar w-[88%]" role="progressbar" data-width="88">
                        <span>88%</span>
                      </div>
                    </div>
                  </div>
                  <div className="progress-box">
                    <h5 className="">Investment Advisory</h5>
                    <div className="progress">
                      <div
                        className="progress-bar w-[95%]"
                        role="progressbar"
                        data-width="95"
                        // style="width: 95%;"
                      >
                        <span>95%</span>
                      </div>
                    </div>
                  </div>
                  <div className="progress-box">
                    <h5>Stock Brokerage</h5>
                    <div className="progress">
                      <div
                        className="progress-bar w-[90%] "
                        role="progressbar"
                        data-width="90"
                        // style="width: 90%;"
                      >
                        <span>90%</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div
            className="expertise-content text-light h-[500px] w-[1170px] rounded-xl bg-[url('/images/imgggg.png')] bg-cover bg-center"
            // style="background-image: url(assets/img/2440x1578.png);"
          >
            <div className="row flex justify-between">
              <div className="col-lg-4 single-item basis-1/3">
                <div className="item">
                  <div className="content_ flex h-[350px] flex-col justify-end">
                    <h3 className="">16</h3>
                    <p></p>
                    <h4 className="">YEARS OF EXPERIENCE.</h4>
                    <p></p>
                  </div>
                </div>
              </div>

              <div className="col-lg-4 single-item basis-1/3">
                <div className="item">
                  <div className="content_ flex h-[350px] flex-col justify-end">
                    <h3>55</h3>
                    <p></p>
                    <h4 className="">STATE LICENSES</h4>
                    <p></p>
                  </div>
                </div>
              </div>

              <div className="col-lg-4 single-item basis-1/3">
                <div className="item">
                  <div className="content_ flex h-[350px] flex-col justify-end">
                    <h3>4 | 3</h3>
                    <p></p>
                    <h4> EXAM PASSED | FIRMS </h4>
                    <p></p>
                  </div>
                </div>
              </div>
            </div>

            <div
              className="fixed-shape bg-[url('/images/13.png')] bg-cover bg-center"
              // style="background-image: url(assets/img/shape/13.png);"
            ></div>
          </div>
        </div>
      </div>

      <div
        id="contact"
        className="contact-area default-padding extra-margin bg-theme inc-shape my-[120px] py-[120px]"
      >
        <div className="container max-w-[1200px]">
          <div className="row align-center -mx-[15px] flex flex-wrap items-center">
            <div className="col-lg-5 info basis-[41.666667%]">
              <div className="content">
                <h2 className="">CONTACT</h2>
                <p>"Need a session?"</p>
                <ul>
                  <li>
                    <i className="fas fa-envelope"></i>
                    <p className="">hello@lisaellenshaw.com</p>
                  </li>
                </ul>
              </div>
            </div>
            <div className="col-lg-6 offset-lg-1 contact-form-box ml-[8.333333%] basis-1/2">
              <div className="form-box">
                <form action="https://formsubmit.co/hello@lisaellenshaw.com" method="POST">
                  <div className="row">
                    <div className="col-lg-12">
                      <div className="form-group">
                        <input
                          className="form-control text-white placeholder-white outline-0 ring-0"
                          id="name"
                          name="name"
                          placeholder="Name"
                          type="text"
                        />
                        <span className="alert-error"></span>
                      </div>
                    </div>
                  </div>
                  <div className="row mt-4 grid grid-cols-2 gap-8">
                    <div className="col-lg-6">
                      <div className="form-group">
                        <input
                          className="form-control text-white placeholder-white outline-0 ring-0"
                          id="email"
                          name="email"
                          placeholder="Email*"
                          type="email"
                        />
                        <span className="alert-error"></span>
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="form-group">
                        <input
                          className="form-control text-white placeholder-white outline-0 ring-0"
                          id="phone"
                          name="phone"
                          placeholder="Phone"
                          type="text"
                        />
                        <span className="alert-error"></span>
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="form-group">
                        <input
                          className="form-control text-white placeholder-white outline-0 ring-0"
                          id="location"
                          name="location"
                          placeholder="Location"
                          type="text"
                        />
                        <span className="alert-error"></span>
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="form-group">
                        <input
                          className="form-control text-white placeholder-white outline-0 ring-0"
                          id="subject"
                          name="subject"
                          placeholder="Subject"
                          type="text"
                        />
                        <span className="alert-error"></span>
                      </div>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-lg-12">
                      <div className="form-group comments">
                        <textarea
                          className="form-control text-white placeholder-white outline-0 ring-0"
                          id="comments"
                          name="comments"
                          placeholder="Book a session Today *"
                        ></textarea>
                      </div>
                    </div>
                  </div>
                  <div className="row mt-4">
                    <div className="col-lg-12">
                      <button
                        type="submit"
                        name="submit"
                        id="submit"
                        className="flex items-center gap-3"
                      >
                        Send Message{' '}
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          height="1em"
                          viewBox="0 0 512 512"
                          className=""
                          fill="#1273eb"
                        >
                          <path d="M498.1 5.6c10.1 7 15.4 19.1 13.5 31.2l-64 416c-1.5 9.7-7.4 18.2-16 23s-18.9 5.4-28 1.6L284 427.7l-68.5 74.1c-8.9 9.7-22.9 12.9-35.2 8.1S160 493.2 160 480V396.4c0-4 1.5-7.8 4.2-10.7L331.8 202.8c5.8-6.3 5.6-16-.4-22s-15.7-6.4-22-.7L106 360.8 17.7 316.6C7.1 311.3 .3 300.7 0 288.9s5.9-22.8 16.1-28.7l448-256c10.7-6.1 23.9-5.5 34 1.4z" />
                        </svg>
                      </button>
                    </div>
                  </div>

                  <div className="col-lg-12 alert-notification">
                    <div id="message" className="alert-msg"></div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      <footer className="bg-dark text-light">
        <div className="container">
          <div className="f-items default-padding py-[120px]">
            <div className="row -mx-[15px] flex flex-wrap">
              <div className="col-lg-4 col-md-6 item basis-1/3">
                <div className="f-item about ">
                  <img src="/images/logo-light.png" alt="Logo" className="" />
                  <p>LISA ELLEN SHAW</p>
                </div>
              </div>

              <div className="col-lg-3 col-md-6 item contact_side basis-1/4">
                <div className="f-item contact-widget">
                  <h4 className="widget-title">Contact Info</h4>
                  <div className="address">
                    <ul>
                      <li>
                        <div className="icon">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            height="1em"
                            viewBox="0 0 512 512"
                            className="space_it"
                            fill="#1273eb"
                          >
                            <path d="M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z" />
                          </svg>
                        </div>
                        <div className="content">
                          <strong className="text-white">Email:</strong>
                          <br />
                          <a href="mailto:hello@lisaellenshaw.com">hello@lisaellenshaw.com</a>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="footer-bottom">
          <div className="container max-w-[1200px]">
            <div className="footer-bottom-box">
              <div className="row -mx-[15px] flex flex-wrap">
                <div className="col-lg-6">
                  <p className="">© Copyright 2022. All Rights Reserved by Lisa Ellen Shaw.</p>
                </div>
                <div className="col-lg-6 link text-right"></div>
              </div>
            </div>
          </div>
        </div>
      </footer>

      <style jsx>{`
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600&family=Poppins:wght@300;400;500;600;700&display=swap');

        .content h4 {
          text-transform: uppercase;
          color: #1273eb;
          font-size: 20px;
          font-family: 'Poppins', sans-serif;
          font-weight: 600 !important;
          margin-bottom: 25px;
          background: linear-gradient(90deg, rgba(18, 115, 235, 1) 0%, rgba(62, 220, 251, 1) 37%);
          -webkit-background-clip: text;
          -moz-background-clip: text;
          background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .content h2 {
          font-weight: 600;
          font-size: 60px;
          font-family: 'Poppins', sans-serif;
          margin: 0;
          color: #232323;
          line-height: 1.1;
        }
        .content a {
          margin-top: 40px;
          text-decoration: none;
        }

        .btn.btn-gradient {
          position: relative;
          z-index: 1;
          color: #ffffff;
        }
        .btn.btn-gradient::after {
          position: absolute;
          left: 0;
          top: 0;
          content: '';
          height: 100%;
          width: 100%;
          background-image: linear-gradient(to right, #1273eb, #18ebeb, #1273eb);
          background-size: 220% 150%;
          text-transform: uppercase;
          display: inline-block;
          color: #ffffff !important;
          background-color: #1273eb;
          z-index: -1;
          transition: all 0.35s ease-in-out;
        }

        .btn-md {
          padding: 17px 42px;
        }
        .btn {
          display: inline-block;
          font-weight: 600;
          text-transform: capitalize;
          -webkit-transition: all 0.35s ease-in-out;
          -moz-transition: all 0.35s ease-in-out;
          -ms-transition: all 0.35s ease-in-out;
          -o-transition: all 0.35s ease-in-out;
          transition: all 0.35s ease-in-out;
          overflow: hidden;
          border-radius: 8px;
          font-size: 15px;
          text-transform: capitalize;
          letter-spacing: 0.5px;
          outline: medium none;
          font-family: 'Poppins', sans-serif;
        }
        .banner-area.auto-height .shape-thumb img {
          padding: 50px;
          margin-top: 120px;
          padding-bottom: 0;
        }
        #services .container {
          display: flex;
          flex-direction: column;
          justify-content: center;
          justify-items: center;
          align-items: center;
          text-align: center;
          margin-bottom: 60px;
        }

        .site-heading h4 {
          text-transform: uppercase;
          font-weight: 700;
          color: #1273eb;
          position: relative;
          z-index: 1;
          display: inline-block;
          background: linear-gradient(90deg, rgba(18, 115, 235, 1) 30%, rgba(4, 215, 242, 1) 100%);
          -webkit-background-clip: text;
          -moz-background-clip: text;
          background-clip: text;
          -webkit-text-fill-color: transparent;
          font-family: 'Poppins', sans-serif;
          font-size: 20px;
        }
        .site-heading h2 {
          display: block;
          font-weight: 700;
          font-family: 'Poppins', sans-serif;
          font-size: 36px;
          position: relative;
          margin-bottom: 0;
          color: #ffffff;
        }

        .site-heading .devider {
          display: inline-block;
          width: 50px;
          height: 2px;
          background: #1273eb;
          position: relative;
          z-index: 1;
          left: 10px;
        }
        .site-heading .devider:before {
          position: absolute;
          left: -15px;
          top: 0;
          content: '';
          height: 2px;
          width: 10px;
          background: #1273eb;
        }

        /* styles.css */
        .parent-container {
          overflow-x: auto;
          scrollbar-width: thin; /* or set to 0 for Firefox */
        }

        .parent-container::-webkit-scrollbar {
          width: 6px; /* Set the width of the scrollbar (adjust as needed) */
        }

        .parent-container::-webkit-scrollbar-thumb {
          background-color: transparent; /* Make the thumb transparent */
        }

        .parent-container::-webkit-scrollbar-track {
          background-color: transparent; /* Make the track transparent */
        }
        /* For Webkit-based browsers (Chrome, Safari and Opera) */
        .scrollbar-hide::-webkit-scrollbar {
          display: none;
        }

        /* For IE, Edge and Firefox */
        .scrollbar-hide {
          -ms-overflow-style: none; /* IE and Edge */
          scrollbar-width: none; /* Firefox */
        }

        .image-container::before {
          content: '';
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          background: rgba(0, 0, 0, 0.3);
          z-index: 1;
        }

        .info-header {
          display: block;
          font-weight: 500;
          font-family: 'Poppins', sans-serif;
          font-size: 20px;
          position: relative;
          margin-bottom: 0;
          color: #ffffff;
        }

        .info-para {
          color: #cccccc;
          margin: 0 0 15px;
          text-transform: none;
          font-weight: 400;
          margin-top: 13px;
        }
        .thumbs-services-area .item {
          position: relative;
          z-index: 1;
          margin: 0 15px;
        }

        .thumbs-services-area .item::after {
          position: absolute;
          left: -15px;
          top: 80px;
          right: -15px;
          content: '';
          bottom: 0;
          z-index: -1;
          border-radius: 7px;
        }

        .bg-gray {
          background: linear-gradient(
            90deg,
            rgba(237, 245, 255, 1) 0%,
            rgba(204, 223, 247, 1) 100%
          );
        }

        .about-us-area .about-items .thumb::after {
          position: absolute;
          left: 0;
          top: 0;
          content: '';
          height: 50%;
          width: 25px;
          background: #1273eb;
          z-index: -1;
          border-radius: 8px;
        }

        .about-us-area .about-items .thumb h2 {
          bottom: 50px;
          margin: 0;
          background: #ffffff;
          padding: 37px;
          padding-top: 30px;
          font-weight: 600;
          line-height: 1.1;
          color: #666666;
          border-radius: 8px;
        }

        .about-us-area .info h2 {
          font-weight: 600;
          margin-bottom: 25px;
          font-size: 36px;
          font-family: 'Poppins', sans-serif;
          font-weight: 600 !important;
          color: #232323;
        }

        .about-us-area .info p {
          margin-bottom: 25px;
          font-size: 15px;
          font-family: 'Open Sans', sans-serif;
          color: #666666;
        }

        .about-us-area .author .signature {
          border-right: 1px solid #999999;
          padding-right: 20px;
          margin-right: 20px;
        }

        .about-us-area .author h5 {
          font-weight: 600;
          margin-bottom: 5px;
          font-family: 'Poppins', sans-serif;
          font-size: 18px;
        }

        .about-us-area .author span {
          font-family: 'Open Sans', sans-serif;
          font-size: 15px;
          color: #666666;
        }

        .about-us-area .about-items .info ul {
          margin-top: 30px;
        }

        .about-us-area .about-items .info ul li {
          margin-top: 10px;
          position: relative;
          z-index: 1;
          font-family: 'Poppins', sans-serif;
          color: #232323;
          font-weight: 500;
          font-size: 15px;
        }

        .expertise-area .item-heading {
          margin-bottom: 60px;
        }

        .expertise-area .info {
          padding-right: 35px;
        }

        .expertise-area .info h4 {
          text-transform: uppercase;
          color: #1273eb;
          font-weight: 600;
          background: linear-gradient(90deg, rgba(18, 115, 235, 1) 30%, rgba(4, 215, 242, 1) 100%);
          -webkit-background-clip: text;
          -moz-background-clip: text;
          background-clip: text;
          -webkit-text-fill-color: transparent;
          display: inline-block;
          font-size: 20px;
        }

        .skill-items .progress-box {
          margin-bottom: 40px;
        }

        .skill-items .progress-box h5 {
          text-transform: capitalize;
          font-weight: 600;
          margin-bottom: 5px;
          text-align: left;
          position: relative;
          z-index: 1;
          font-size: 16px;
        }

        .skill-items .progress-box .progress {
          background: transparent;
          border-bottom: 2px solid #e7e7e7;
          box-shadow: inherit;
          border-radius: inherit;
          overflow: inherit;
        }

        .progress {
          display: -ms-flexbox;
          display: flex;
          height: 1rem;
          overflow: hidden;
          font-size: 0.75rem;
          background-color: #e9ecef;
          border-radius: 0.25rem;
        }

        .skill-items .progress-box .progress .progress-bar {
          height: 6px;
          border-radius: 30px;
          background: linear-gradient(90deg, rgba(18, 115, 235, 1) 30%, rgba(4, 215, 242, 1) 100%);
          top: 12px;
          position: relative;
          overflow: inherit;
        }

        .skill-items .progress-box .progress .progress-bar span {
          position: absolute;
          right: 0;
          top: -40px;
          display: block;
          font-size: 15px;
          color: #232323;
          font-weight: 600;
          font-family: 'Poppins', sans-serif;
        }

        .expertise-content {
          background-size: cover;
          background-position: center;
          position: relative;
          border-radius: 8px;
        }

        .expertise-area .expertise-content .single-item {
          border-right: 1px solid rgba(255, 255, 255, 0.6);
          z-index: 1;
          background: linear-gradient(
            to bottom,
            rgba(0, 0, 0, 0.107) 0%,
            rgba(0, 0, 0, 0.782) 100%
          );
        }

        .expertise-area .expertise-content .item {
          padding: 50px;
          padding-top: 450px;
          position: relative;
          z-index: 1;
        }

        .expertise-area .expertise-content .content_ {
          position: absolute;
          transition: all 0.35s ease-in-out;
          transform: translateY(5px);
          left: 50px;
          right: 50px;
          bottom: 50px;
        }

        .expertise-area .expertise-content .single-item .item .content_:hover {
          position: absolute;
          transition: all 0.35s ease-in-out;
          transform: translateY(-100px);
          left: 50px;
          right: 50px;
          bottom: 50px;
        }

        .expertise-area .expertise-content .content_ h3 {
          font-size: 27px;
          margin-bottom: 15px;
          font-weight: normal;
          line-height: 1.2;
          font-family: 'Poppins', sans-serif;
          letter-spacing: 0;
          margin: 0;
        }

        .expertise-area .expertise-content .content_ h4 {
          font-weight: 600;
          font-size: 20px;
          margin-bottom: 15px;
        }

        .expertise-content .fixed-shape {
          position: absolute;
          left: -180px;
          bottom: -120px;
          height: 350px;
          width: 350px;
          background-size: contain;
          background-repeat: no-repeat;
          z-index: -1;
        }
        .text-light {
          color: #f8f9fa !important;
          line-height: 1.2;
          font-family: 'Poppins', sans-serif;
          letter-spacing: 0;
          margin: 0;
        }

        .contact-area {
          position: relative;
          z-index: 1;
        }

        .bg-theme {
          background-color: #1273eb;
        }

        .contact-area::before {
          position: absolute;
          right: 0;
          top: 0;
          content: '';
          height: 100%;
          width: 120px;
          background: #ffffff !important;
          z-index: -1;
        }

        .contact-area::after {
          position: absolute;
          left: 0;
          top: 0;
          content: '';
          height: 100%;
          width: 120px;
          background: #ffffff;
          z-index: -1;
        }

        .contact-area .info .content {
          padding: 50px;
          background: #ffffff;
          position: relative;
          z-index: 1;
          padding-left: 80px;
          padding-top: 80px;
        }

        .contact-area .info h2 {
          font-weight: 600;
          margin-bottom: 30px;
          font-size: 36px;
          font-family: 'Poppins', sans-serif;
        }

        .contact-area .info p {
          color: #666666;
          margin: 0 0 15px;
          text-transform: none;
          font-family: 'Poppins', sans-serif;
          font-weight: 400;
        }

        .contact-area .info ul {
          display: block;
          margin-top: 35px;
          margin: 0;
          list-style-type: none;
        }
        .contact-area .info .content::after {
          position: absolute;
          right: -30px;
          top: 30px;
          content: '';
          height: 100%;
          width: 100%;
          background: rgba(255, 255, 255, 0.2);
          z-index: -1;
        }
        .form-control {
          display: block;
          width: 100%;
          height: calc(1.5em + 0.75rem + 2px);
          padding: 0.375rem 0.75rem;
          font-size: 1rem;
          font-weight: 400;
          line-height: 1.5;
          background-color: #fff;
          background-clip: padding-box;
          border: 1px solid #ced4da;
          border-radius: 0.25rem;
          transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }
        .contact-area .form-box input,
        .contact-area .form-box textarea {
          padding: 20px;
          padding-left: 0;
          border: none;
          box-shadow: inherit;
          background: transparent;
          border-bottom: 1px solid rgba(255, 255, 255, 0.4);
          color: #ffffff !important;
          border-radius: inherit;
        }

        .contact-area .form-box textarea {
          min-height: 180px;
        }

        .contact-area .form-box button {
          padding: 15px 42px;
          border-radius: 5px;
          background: #ffffff;
          font-weight: 600;
          color: #1273eb;
        }

        .bg-dark {
          background-color: #1b1b1b !important;
        }
        footer {
          position: relative;
          z-index: 1;
        }

        footer .f-items .f-item.about {
          border-right: 1px solid rgba(255, 255, 255, 0.1);
          padding-right: 40px;
          margin-right: 10px;
        }

        footer .widget-title,
        footer img {
          margin-bottom: 30px;
          font-weight: 600;
        }

        footer p {
          color: #a0a2a6 !important;
        }

        .contact_side {
          position: relative;
          width: 100%;
          padding-right: 15px;
          padding-left: 15px;
        }

        footer .widget-title {
          margin-bottom: 30px;
          font-weight: 600 !important;
          font-size: 20px;
          color: #ffffff;
          font-weight: normal;
          line-height: 1.2;
          font-family: 'Poppins', sans-serif;
          letter-spacing: 0;
        }

        footer .f-items .f-item .address li:last-child {
          margin-bottom: -8px;
        }

        footer .f-items .f-item .address li {
          display: flex;
          margin-bottom: 25px;
        }
        footer .f-items .f-item .address li .space_it {
          display: inline-block;
          margin-right: 20px;
          color: #ffffff;
          font-size: 24px;
          color: #1273eb;
          position: relative;
          top: 5px;
        }

        .fa-envelope:before {
          content: '\f0e0';
        }

        footer .f-items .f-item .address li .content,
        footer .f-items .f-item .address li .content a {
          color: #a0a2a6;
        }

        footer .footer-bottom {
          overflow: hidden;
        }
        footer .footer-bottom-box {
          padding: 50px 0;
          padding-right: 80px;
          position: relative;
          z-index: 1;
        }

        footer .footer-bottom-box::after {
          position: absolute;
          right: 0;
          top: 0;
          content: '';
          height: 100%;
          width: 400%;
          background: #24282b;
          z-index: -1;
          opacity: 0.8;
          clip-path: polygon(0 0, 99% 0, 100% 100%, 10% 100%);
        }
        footer::after {
          position: absolute;
          right: 0;
          top: 0;
          content: '';
          height: 400px;
          width: 400px;
          background: url('/images/map.svg');
          background-size: cover;
          background-repeat: no-repeat;
          z-index: -1;
          opacity: 0.3;
        }
      `}</style>
    </>
  )
}

export default Index
